### PR TITLE
Use latest Selenium images in images

### PR DESCRIPTION
**Pull request by tinez**
With [1] merged we should get fresh Selenium images every month/on
demand.

[1] https://github.com/oVirt/ost-images/pull/49

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

### CODE REVIEW

**Comment by michalskrivanek** [comment]
but won't that break when we have
CHROME_VERSION = '94.0.4606.81'
FIREFOX_VERSION = '93.0'
? does it not need to match?

**Comment by tinez** [comment]
> but won't that break when we have...

That's a good question. I'd merge this and see how OST will behave. If possible I'd vote for removing the versions from OST code, so we don't have to sync it all the time.

**Comment by michalskrivanek** [comment]
> > but won't that break when we have...
> 
> That's a good question. I'd merge this and see how OST will behave. If possible I'd vote for removing the versions from OST code, so we don't have to sync it all the time.

IIRC they matter. Or at least they used to in selenium <4. Please do try that

**Review by michalskrivanek — APPROVED** [review]
until some selenium incompatiblity breaks us...

**Pull request merged**
