### PR TITLE
host: Add vdsm-hook-log-console package to hosts/nodes

### PR DESCRIPTION
**Pull request by tinez**
We need that package to dump HE logs to a file in OST runs.

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

### CODE REVIEW

**Review by michalskrivanek — COMMENTED** [review]
LGTM, but need to wait for vdsm d/s build for rhel

**Comment by didib** [comment]
+1, but perhaps also configure it?

**Comment by michalskrivanek** [comment]
generally we try to avoid too many configurations here as it's disconnected from OST repo. We try to do the bare minimum so we do not have to install additional packages and are able to boot OST VMs.
I think it would be best to do the configuration in setup_host.sh in OST

**Comment by michalskrivanek** [comment]
we need to wait for rhel build of the hook

**Pull request merged**
